### ISSUE TITLE
질문~~

### ISSUE THREAD

**Issue by rebehayan** [rebehayan/Yeongdeungpo2024#2]
이거 잘안되요~~ ㅠㅠ

```html
        li {
          border: 1px solid blue;
          padding: 10px;
        }
```

CSS도 질문합니다.
```css
.align-both {
  display: flex;
  justify-content: space-between;
}
```
